version: "2.1"

services:
  namenode:
    mem_limit: 300m
    mem_reservation: 100m
    build: ./namenode
    container_name: namenode
    volumes:
      - hadoop_namenode:/hadoop/dfs/name
      - ./data/:/hadoop-data/input
      - ./map_reduce/:/hadoop-data/map_reduce
    environment:
      - CLUSTER_NAME=test
    ports:
      - "9870:9870"
      - "8020:8020"
    networks:
      - hadoop_network
    storage_opt:
      size: '200m'

  resourcemanager:
    build: ./resourcemanager
    mem_limit: 300m
    mem_reservation: 100m
    container_name: resourcemanager
    restart: on-failure
    depends_on:
      - namenode
      - datanode1
      - datanode2
    ports:
      - "8089:8088"
    networks:
      - hadoop_network
    storage_opt:
      size: '200m'

  historyserver:
    build: ./historyserver
    mem_limit: 300m
    mem_reservation: 100m
    container_name: historyserver
    depends_on:
      - namenode
      - datanode1
      - datanode2
    volumes:
      - hadoop_historyserver:/hadoop/yarn/timeline
    ports:
      - "8188:8188"
    networks:
      - hadoop_network
    storage_opt:
      size: '200m'

  nodemanager1:
    build: ./nodemanager
    mem_limit: 300m
    mem_reservation: 100m
    container_name: nodemanager1
    depends_on:
      - namenode
      - datanode1
      - datanode2
    ports:
      - "8042:8042"
    networks:
      - hadoop_network
    storage_opt:
      size: '200m'

  datanode1:
    build: ./datanode
    mem_limit: 300m
    mem_reservation: 100m
    container_name: datanode1
    depends_on:
      - namenode
    volumes:
      - hadoop_datanode1:/hadoop/dfs/data
    networks:
      - hadoop_network
    storage_opt:
      size: '200m'

  datanode2:
    build: ./datanode
    mem_limit: 300m
    mem_reservation: 100m
    container_name: datanode2
    depends_on:
      - namenode
    volumes:
      - hadoop_datanode2:/hadoop/dfs/data
    networks:
      - hadoop_network
    storage_opt:
      size: '200m'

volumes:
  tmpfs:
    driver: local
    driver_opts:
      o: "size=100m,uid=1000"
      device: tmpfs
      type: tmpfs
  hadoop_namenode:
  hadoop_datanode1:
  hadoop_datanode2:
  hadoop_historyserver:


networks:
  hadoop_network:
    name: hadoop_network
